### ISSUE TITLE
Conflicts with rule #9 of PUBG

### ISSUE THREAD

**Issue by Snaacky** [Snaacky/Crouchjump#1]
People have been asking if this program can be considered a cheat or a hack so I wanted to use this space to voice my own opinion regarding this.

The rule in question:

> Do not cheat: do not use third party programs, macros, client-side hacks, edited game files or anything else that may give you an unfair advantage in the game. This includes promoting or posting links to websites that provide or promote cheats or hacks.

First of all, I would like to state that this program does not interact like a normal "cheat" would. It does not read or write to memory at all. It does not hook into the game at any point. It does not interact with DirectX APIs, it has no similarities with real cheats.

A gigantic problem with the rule that this project may potentially violate is that PlayerUnknown himself has contradicted the rules of conduct and personally told players that by proxy, they are free to violate this rule. 

The rule clearly states:
> or anything else that may give you an unfair advantage in the game

Interestingly, PU has [personally okayed](https://twitter.com/playerunknown/status/851074602084192258?lang=en) the use of [ReShade](http://reshade.me/) which is a program that injects itself in the same way that cheats do into games. Not only does ReShade inject itself in a way like cheats do, however it offers graphical modifications such as "clarity" and is known in the PUBG community for giving a big advantage in terms of visibility and clarity versus players who do not also use ReShade, directly contradicting rule #9. 

Use of third-party programs for being able to have better visibility and clarity over other players is okay but being able to jump through select few windows isn't okay? Seems a little odd, no?

On another note, hardware manufacturers such as Razer, Logitech, SteelSeries, just to name a few, ship their hardware with features and options that can be used to re-create this project within their driver software. If macros were considered cheats, would PC hardware companies willingly be shipping cheats with their hardware?

**Comment by thePeterG** [comment]
I agree 100%.

**Comment by thePeterG** [comment]
also of interest https://www.reddit.com/r/PUBATTLEGROUNDS/comments/72396a/iama_poopiequeen_ama/dnff4ez/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=PUBATTLEGROUNDS

Apparently, macros are not being banned ATM.

**Comment by Snaacky** [comment]
Bluehole are currently not banning users of macros. Should this change, the issue will be re-opened.
